### PR TITLE
Reset ourStopped on project data creation

### PR DESCRIPTION
**Pull request by brian-mcnamara**

### CODE REVIEW

**Comment by brian-mcnamara** [comment]
Ive extended this and am creating multiple project data instances (not at once, just over the duration of the JVM). I need this to reset the stopped variable to be able to recollect traces.

**Comment by brian-mcnamara** [comment]
Absolutely, that will work perfectly as well. Thanks for the suggestion.

**Comment by brian-mcnamara** [comment]
Merged as b02ba61

**Comment by zuevmaxim** [comment]
OK, then the issue is fixed by [b02ba61](https://github.com/JetBrains/intellij-coverage/commit/b02ba6156cac9e0fa92cc446fc39c4d0569b30b0)

**Pull request closed without merging**
