### PR TITLE
Fix IDEA-258647

### PR DESCRIPTION
**Pull request by zuevmaxim**
https://youtrack.jetbrains.com/issue/IDEA-258647

### CODE REVIEW

**Comment by akozlova** [comment]
Frankly speaking I would rather disable instrumenting classes from bootstrap loader and remove them from excludes we have.  Do you see any problems with that?

**Comment by zuevmaxim** [comment]
> Frankly speaking I would rather disable instrumenting classes from bootstrap loader and remove them from excludes we have. Do you see any problems with that?

In this case we lose control on switching on/off some packages for example `javax.*, org.xml` and some others.
Also it does not fix the `IOException` case (I updated the issue): we may be asked about class from the bootstrap class loader while we have a not null class loader which cannot find the class.
In my test all classes with null class loader could be found with this fix.
With current fix the number of thrown IOExceptions decreases dramatically for my test(from 684 to 5).

**Comment by akozlova** [comment]
Current fix is very suspicious. If class loader can't find class and do not delegate to system class loader, it's the author decision? Are you sure this case exists in real world (outside of your tests)?

**Comment by zuevmaxim** [comment]
By my tests I mean running some tests from IDEA project, namely Community java/compiler tests. Switching off a call to  system class loader increases the number of unsuccessful results(java.io.IOException: Class ... not found).

Running some other tests I realised that this case is applicable only to one package that I occasionally chose first.

`java.io.IOException: Class java/util/List not found` 
java/util/List is in bootstrap loader, while class that is instrumented now (com.intellij.testFramework.UsefulTestCase) is not in bootstrap loader.

**Comment by akozlova** [comment]
>Switching off a call to system class loader increases the number of unsuccessful results(java.io.IOException: Class ... not found).

It's not the goal to decrease number of reported IOE exceptions, e.g. you can skip logging them in this case. You need to find common super class for 2 classes which can be loaded by *this* class loader. If class loader can't load a class from system loader, it may be intentional and I don't think that it's a good idea load it explicitly. Could you please check which class loader in IDEA's tests can't load java.util.List and where is this class loader created? 
Thanks

**Comment by zuevmaxim** [comment]
Now I cannot reproduce this case anymore(I don't know what has changed in my test configuration), so I'm going to fix only NPE case. 
Back again to the first fix version, I'm not sure that we must ignore all classes from bootstrap class loader as it isn't nessesary but may disable some interesting classes. Explicit excludes look better for me.

**Comment by akozlova** [comment]
ok, let's live with the first fix

**Pull request merged**
