### PR TITLE
Add Kotlin tests

### PR DESCRIPTION
**Pull request by zuevmaxim**

### CODE REVIEW

**Comment by gorrus** [comment]
why #13 is included here?

**Comment by zuevmaxim** [comment]
> why #13 is included here?

Because there is no point in merging tests into master without #13. #13 is a kind of fix up for tests PR.
Also it was easier to base #13 on this PR.

**Comment by akozlova** [comment]
I don't really want to check the test data, what bothers me though, I completely don't understand the state of work with different PRs in different state of completion.

**Comment by akozlova** [comment]
What bothers me here, I completely don't understand the state of work with different PRs. Should I just check the branch instead? Or how to proceed here? Thanks

**Review by gorrus — APPROVED** [review]

**Pull request merged**
